"""The GameGPT wire contract.

These models are frozen as of Phase 1 and every subagent codes against them.
If a shape needs to change, the orchestrator changes it here and re-generates
`openapi.json` — subagents do not edit this file.
"""

from __future__ import annotations

from enum import Enum
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, Field


# ─────────────────────────── /api/recommend ───────────────────────────


class RecommendRequest(BaseModel):
    """Body for POST /api/recommend."""

    query: str = Field(..., min_length=1, max_length=500,
                        description="Natural-language description of what to play.")


class GameCandidate(BaseModel):
    """A game pulled from the vector store before the LLM ranks it.

    Internal DTO passed EmbeddingService -> VectorStore -> Dedup -> LLM.
    """

    game_id: UUID
    title: str
    description: Optional[str] = None
    genres: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    developer: Optional[str] = None
    review_score: Optional[float] = None
    steam_appid: Optional[int] = None
    similarity: Optional[float] = Field(
        default=None, description="Cosine similarity to the query embedding, 0-1."
    )


class Recommendation(BaseModel):
    """One ranked recommendation returned to the client."""

    rank: int = Field(..., ge=1, description="1 is the best match.")
    game_id: Optional[UUID] = None
    title: str
    reason: str = Field(..., description="Why this fits the query. Never empty.")
    steam_appid: Optional[int] = None
    review_score: Optional[float] = None


class RecommendResponse(BaseModel):
    """Body returned from POST /api/recommend."""

    query_id: UUID = Field(..., description="Persisted queries.id; echo it into feedback.")
    query: str
    recommendations: list[Recommendation]


# ─────────────────────────── /api/feedback ───────────────────────────


class Vote(str, Enum):
    up = "up"
    down = "down"


class FeedbackRequest(BaseModel):
    """Body for POST /api/feedback. Returns 204, persists a row."""

    query_id: UUID
    game_id: Optional[UUID] = None
    title: str = Field(..., description="Denormalized so feedback is legible without a join.")
    rank: Optional[int] = None
    vote: Vote


# ─────────────────────── /api/library + /sync ───────────────────────


class LibrarySyncRequest(BaseModel):
    """Body for POST /api/library/sync. Pasted public steamID64."""

    steam_id: str = Field(..., min_length=1, max_length=32,
                          description="Public steamID64, e.g. 76561197960287930.")


class LibrarySyncResponse(BaseModel):
    """Result of a sync: how many rows landed and where they came from."""

    synced: int
    source: str = Field(..., description="'steam' for a real API call, 'seed' for the fallback.")


class LibraryItem(BaseModel):
    """One owned game in the user's cross-platform library."""

    game_id: Optional[UUID] = None
    title: str
    steam_appid: Optional[int] = None
    platform: str = "steam"


class LibraryResponse(BaseModel):
    """Body returned from GET /api/library."""

    items: list[LibraryItem]
